const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs');const path=require('path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let markup=fs.readFileSync(root+'/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,'');
const consoleLog=new VirtualConsole();const errors=[];consoleLog.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(markup,{url:'https://purrity.example/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:consoleLog});
const w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.pmMathFailed=true;w.print=()=>{};
for(const name of ['data','curriculum','base','math','study']){const script=w.document.createElement('script');script.textContent=fs.readFileSync(root+'/assets/'+name+'.js','utf8');w.document.body.append(script)}
const run=code=>w.eval(code);const doc=w.document;let checks=0;
function check(label,fn){try{fn();checks++;console.log('PASS',label)}catch(e){console.error('FAIL',label);throw e}}
function route(p){w.history.replaceState(null,'','#/'+p);run('render()')}
function click(selector){const el=doc.querySelector(selector);assert.ok(el,'Missing '+selector);el.click()}
check('dashboard and resources',()=>{assert.match(doc.querySelector('.hero h2').textContent,/nurrub/);for(const ref of [...doc.querySelectorAll('script[src],link[rel=stylesheet]')])assert.ok(fs.existsSync(path.resolve(root,ref.getAttribute('src')||ref.getAttribute('href'))))});
check('new hash route listener',()=>{w.history.replaceState(null,'','#/curriculum');w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(doc.querySelectorAll('.coverage-card').length,15)});
check('verified curriculum and explicit limitations',()=>{route('curriculum');assert.match(doc.querySelector('#content').textContent,/19. mai 2027/);assert.match(doc.querySelector('#content').textContent,/ei õnnestunud kontrollida/);assert.match(doc.querySelector('#content').textContent,/Ma13/);click('[data-curriculum=national]');assert.equal(doc.querySelectorAll('.coverage-card').length,14);assert.equal(doc.querySelectorAll('.source-list a').length,6)});
check('all topic routes and both languages',()=>{for(const language of ['et','en']){run(`lang='${language}'`);const paths=run('TOPICS.map(r=>r.path)');for(const p of paths){route(p);assert.ok(doc.querySelector('[data-confidence]'));route(p+'/formulas');assert.ok(doc.querySelector('.formula-card math'));route(p+'/questions');assert.ok(doc.querySelector('[data-draft]'));assert.ok(doc.querySelector('.answer:not(.show)'));assert.ok(!doc.querySelector('.question > .answer.show'));}}assert.equal(run('TOPICS.length'),26);assert.equal(run('QUESTIONS.length'),66);assert.equal(run('FORMULAS.length'),57)});
check('search no-match and bilingual hits',()=>{assert.equal(run("searchAll('zzzzzznotmath').length"),0);assert.ok(run("searchAll('triangle area').some(r=>r.type==='formula')"));assert.ok(run("searchAll('kolmnurga pindala').some(r=>r.type==='formula')"));assert.ok(run("searchAll('logarithm').some(r=>r.mk==='review')"))});
check('formula bookmarking and notebook',()=>{route('review/equations/formulas');click('[data-save]');assert.ok(run("state.saved.includes('review/equations/f/0')"));route('notebook');click('[data-notebook=saved]');assert.ok(doc.querySelector('.formula'));click('[data-save]');assert.ok(!run("state.saved.includes('review/equations/f/0')"))});
check('draft notes grading and no accidental double count',()=>{route('review/equations/questions');const field=doc.querySelector('[data-draft]');field.value='3x = 18';field.dispatchEvent(new w.Event('input'));assert.equal(run("state.drafts['review/equations/p/0']"),'3x = 18');click('.reveal');assert.equal(doc.querySelector('.reveal').getAttribute('aria-expanded'),'true');const note=doc.querySelector('[data-note]');note.value='Remember to divide';note.dispatchEvent(new w.Event('input'));click('[data-rate=again]');assert.equal(run("state.ratings['review/equations/p/0'].count"),1);click('[data-rate=again]');assert.equal(run("state.ratings['review/equations/p/0'].count"),1);route('notebook');click('[data-notebook=weak]');assert.match(doc.querySelector('#content').textContent,/3x − 7/);assert.equal(doc.querySelector('[data-draft]').value,'3x = 18')});
check('numeric check supports comma and fractions, excludes code',()=>{assert.equal(run("numericValue('1/2')"),.5);assert.equal(run("numericValue('78,2')"),78.2);assert.ok(Number.isNaN(run("numericValue('1/0')")));assert.ok(Number.isNaN(run("numericValue('alert(1)')")));route('review/equations/questions');const input=doc.querySelector('[data-numeric-input]');input.value='6';click('[data-check]');assert.match(doc.querySelector('[data-numeric-result]').textContent,/matches/)});
check('session grades then enables next and resumes',()=>{run("startSession('mixed','review/equations',3)");route('practice');assert.equal(doc.querySelector('#next-session').disabled,true);click('#session-reveal');click('[data-rate=hard]');assert.equal(doc.querySelector('#next-session').disabled,false);route('library');route('practice');assert.equal(doc.querySelector('#next-session').disabled,false);click('#next-session');assert.equal(run('state.session.index'),1);route('library');route('practice');assert.match(doc.querySelector('.page-head p').textContent,/2 \/ 3/);click('#skip-session');click('#skip-session');assert.equal(run('state.session.finished'),true);assert.ok(doc.querySelector('.session-result'))});
check('timed mode keeps solutions hidden and expires safely',()=>{run("startSession('timed','review/logs',3)");route('practice');assert.equal(doc.querySelector('#session-reveal'),null);assert.equal(doc.querySelector('[data-rate]'),null);assert.equal(doc.querySelector('.answer'),null);assert.match(doc.querySelector('#session-clock').textContent,/25:00|24:59/);run('state.session.deadline=Date.now()-1000');route('practice');assert.equal(run('state.session.finished'),true);assert.ok(doc.querySelector('.session-result'))});
check('flashcard recall and scheduling',()=>{route('cards');assert.equal(doc.querySelector('#flash-answer').hidden,true);click('#flip-card');assert.equal(doc.querySelector('#flash-answer').hidden,false);const id=doc.querySelector('[data-rate=good]').dataset.id;click('[data-rate=good]');assert.equal(run(`state.ratings[${JSON.stringify(id)}].grade`),'good');assert.ok(run(`state.ratings[${JSON.stringify(id)}].due > Date.now()`))});
check('state roundtrip, schema filtering and safe text escaping',()=>{const state=JSON.parse(w.localStorage.getItem('pm_study_v2'));assert.equal(state.version,2);assert.equal(run(`validateState(${JSON.stringify(state)}).version`),2);const hostile={version:2,notes:{'review/equations':'<img src=x onerror=alert(1)>'},drafts:{unknown:'junk'},saved:['unknown'],ratings:{'review/equations/p/0':{grade:'good',count:Infinity,due:1,at:1}}};const validated=run(`validateState(${JSON.stringify(hostile)})`);assert.equal(Object.keys(validated.drafts).length,0);assert.equal(validated.saved.length,0);assert.equal(Object.keys(validated.ratings).length,0);run(`state.notes['review/equations']='<img src=x onerror=alert(1)>'`);route('review/equations');assert.equal(doc.querySelector('#topic-note').value,'<img src=x onerror=alert(1)>');assert.equal(doc.querySelector('img'),null);assert.throws(()=>run('validateState({version:9})'))});
check('graph lab updates accessible values',()=>{route('lab');const slider=doc.querySelector('#graph-x');slider.value='0';slider.dispatchEvent(new w.Event('input'));assert.match(doc.querySelector('#graph-values').textContent,/f′\(x₀\) = 0.00/);assert.match(doc.querySelector('#graph-svg').getAttribute('aria-label'),/tangent slope 0/)});
check('glossary bilingual filter',()=>{route('glossary');const field=doc.querySelector('#term-search');field.value='puutuja';field.dispatchEvent(new w.Event('input'));assert.equal(doc.querySelectorAll('.term').length,1);assert.match(doc.querySelector('.term').textContent,/tangent/)});
check('native fallback handles compact fractions and full data',()=>{const output=run("mathMarkup('\\\\frac36')");assert.match(output,/<mn>3<\/mn><mn>6<\/mn>/);const expressions=run("[...FORMULAS.map(r=>r.f.tex),...FORMULAS.flatMap(r=>[r.f.e1.q.et,r.f.e1.a.et,r.f.e2.q.et,r.f.e2.a.et]),...QUESTIONS.flatMap(r=>[r.q.q.et,r.q.a.et])]");for(const expr of expressions){const node=doc.createElement('div');node.innerHTML=run(`mathMarkup(${JSON.stringify(expr)})`);assert.ok(node.querySelector('math'));assert.ok(!node.querySelector('parsererror'))}});
check('backups, focus and unknown routes',()=>{route('settings');assert.ok(doc.querySelector('#import-data'));click('#settings-focus');assert.ok(doc.body.classList.contains('focus-mode'));route('bogus');assert.ok(doc.querySelector('.hero'));assert.equal(errors.length,0)});
run('clearInterval(clock)');dom.window.close();console.log(`${checks} checks passed`);
